url: "https://sinc865.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Sakuya Ota" # the name of your site, e.g. ACME Corp.
description: "太田 朔哉"
